# Generated by Django 6.0 on 2025-12-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Player's display name", max_length=30)),
                ('session_key', models.CharField(help_text='Browser session key to identify player without login', max_length=40)),
                ('board', models.JSONField(default=list, help_text='5x5 grid as 2D array: [[1,2,3,4,5], [6,7,8,9,10], ...]')),
                ('marked_numbers', models.JSONField(default=list, help_text='List of numbers that have been called: [5, 13, 21]')),
                ('is_ready', models.BooleanField(default=False, help_text='Has the player clicked Ready in setup phase?')),
                ('is_host', models.BooleanField(default=False, help_text='Did this player create the room?')),
                ('completed_lines', models.IntegerField(default=0, help_text='Number of Bingo lines completed (need 5 to win)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique room code for joining (e.g., ABC123)', max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('setup', 'Board Setup Phase'), ('playing', 'Game in Progress'), ('finished', 'Game Finished')], default='waiting', help_text='Current state of the game', max_length=10)),
                ('setup_deadline', models.DateTimeField(blank=True, help_text='When the setup phase ends (1 minute after starting)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_turn', models.ForeignKey(blank=True, help_text="Which player's turn is it?", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_in_room', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(help_text='The room this player is in', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'session_key')},
        ),
        migrations.CreateModel(
            name='CalledNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='The number that was called (1-25)')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(help_text='The player who called this number', on_delete=django.db.models.deletion.CASCADE, related_name='numbers_called', to='game.player')),
                ('room', models.ForeignKey(help_text='The room where this number was called', on_delete=django.db.models.deletion.CASCADE, related_name='called_numbers', to='game.room')),
            ],
            options={
                'ordering': ['called_at'],
                'unique_together': {('room', 'number')},
            },
        ),
    ]
