# Generated by Django 6.0 on 2025-12-10 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique room code (e.g., ABC123)', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='False when room is abandoned')),
                ('settings_setup_duration', models.IntegerField(default=60, help_text='Seconds for board arrangement phase')),
                ('settings_turn_duration', models.IntegerField(default=30, help_text='Seconds per turn')),
                ('settings_max_players', models.IntegerField(default=6, help_text='Maximum players allowed (2-15)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created room (null for guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('setup', 'Board Setup Phase'), ('playing', 'Game in Progress'), ('finished', 'Game Finished')], default='waiting', max_length=10)),
                ('called_numbers', models.JSONField(default=list, help_text='List of called numbers [5, 13, 21]')),
                ('turn_deadline', models.DateTimeField(blank=True, help_text='When current turn/phase expires', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.room')),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Browser session for guests', max_length=40, null=True)),
                ('display_name', models.CharField(help_text="Player's display name", max_length=30)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co-host', 'Co-Host'), ('player', 'Player')], default='player', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='False when member leaves room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.room')),
                ('user', models.ForeignKey(blank=True, help_text='Logged in user (null for guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list, help_text='5x5 grid [[1,2,3,4,5], ...]')),
                ('is_ready', models.BooleanField(default=False)),
                ('completed_lines', models.IntegerField(default=0, help_text='Number of completed lines (0-5+)')),
                ('turn_order', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameround')),
                ('room_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_participations', to='game.roommember')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='gameround',
            name='current_turn',
            field=models.ForeignKey(blank=True, help_text='Whose turn is it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_round', to='game.roundplayer'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='game.roundplayer'),
        ),
        migrations.CreateModel(
            name='CalledNumberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='The number called (1-25)')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='game.gameround')),
                ('called_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to='game.roundplayer')),
            ],
            options={
                'ordering': ['called_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('room', 'session_key'), name='unique_room_session'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('room', 'user'), name='unique_room_user'),
        ),
        migrations.AlterUniqueTogether(
            name='roundplayer',
            unique_together={('game_round', 'room_member')},
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('room', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='callednumberhistory',
            unique_together={('game_round', 'number')},
        ),
    ]
