# Generated by Django 6.0 on 2025-12-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundplayer',
            options={'ordering': ['turn_order']},
        ),
        migrations.RemoveField(
            model_name='roundplayer',
            name='completed_lines',
        ),
    ]
