# Generated by Django 6.0 on 2025-12-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roommember',
            name='unique_room_session',
        ),
        migrations.RemoveConstraint(
            model_name='roommember',
            name='unique_room_user',
        ),
    ]
