# Generated by Django 6.0 on 2025-12-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='marked_numbers',
        ),
        migrations.RemoveField(
            model_name='room',
            name='setup_deadline',
        ),
        migrations.AddField(
            model_name='room',
            name='called_numbers',
            field=models.JSONField(default=list, help_text='List of numbers called in the game: [5, 13, 21]'),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for current phase/turn', null=True),
        ),
        migrations.AlterField(
            model_name='callednumber',
            name='room',
            field=models.ForeignKey(help_text='The room where this number was called', on_delete=django.db.models.deletion.CASCADE, related_name='called_numbers_history', to='game.room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='board',
            field=models.JSONField(default=list, help_text='5x5 grid as 2D array: [[1,2,3,4,5], ...]'),
        ),
        migrations.AlterField(
            model_name='player',
            name='completed_lines',
            field=models.IntegerField(default=0, help_text='Number of Bingo lines completed (5 to win)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Has player clicked Ready in setup phase?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='session_key',
            field=models.CharField(help_text='Browser session key to identify player', max_length=40),
        ),
    ]
