# Generated by Django 6.0 on 2025-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayer',
            name='completed_line_indices',
            field=models.JSONField(default=list, help_text='List of completed line indices from winning lines [0,1,5,8]'),
        ),
    ]
