# Generated by Django 6.0 on 2025-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_roundplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='settings_show_score',
            field=models.BooleanField(default=False, help_text='Whether to show bingo score to players of others'),
        ),
        migrations.AlterField(
            model_name='room',
            name='settings_max_players',
            field=models.IntegerField(default=8, help_text='Maximum players allowed (2-15)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='settings_turn_duration',
            field=models.IntegerField(default=20, help_text='Seconds per turn'),
        ),
    ]
