# Generated by Django 6.0 on 2025-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_settings_show_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameround',
            name='winner',
        ),
        migrations.AddField(
            model_name='gameround',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='won_rounds', to='game.roundplayer'),
        ),
    ]
