# Generated by Django 6.0 on 2025-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gameround_winner_gameround_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='callednumberhistory',
            name='is_bot_call',
            field=models.BooleanField(default=False, help_text='True if called by bot'),
        ),
        migrations.AddField(
            model_name='room',
            name='settings_grace_period',
            field=models.IntegerField(default=10, help_text='Seconds of grace period'),
        ),
        migrations.AddField(
            model_name='roommember',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Current WebSocket channel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', max_length=15),
        ),
        migrations.AddField(
            model_name='roommember',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, help_text='When player disconnected', null=True),
        ),
        migrations.AddField(
            model_name='roundplayer',
            name='is_bot_controlled',
            field=models.BooleanField(default=False, help_text='True when player disconnected and bot takes over'),
        ),
    ]
