# Generated by Django 6.0 on 2025-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_callednumberhistory_is_bot_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('removed', 'Removed'), ('left', 'Left'), ('kicked', 'Kicked'), ('banned', 'Banned')], default='connected', max_length=15),
        ),
    ]
