# Generated by Django 6.0 on 2025-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_roommember_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='kicked_count',
            field=models.IntegerField(default=0, help_text='Number of times this member has been kicked'),
        ),
        migrations.AlterField(
            model_name='room',
            name='settings_grace_period',
            field=models.IntegerField(default=15, help_text='Seconds of grace period'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when member is Kicked or Removed'),
        ),
    ]
