# Generated by Django 6.0 on 2025-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_roommember_kicked_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='visibility_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private ')], default='public', help_text='Room visibility type', max_length=10),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('left', 'Left'), ('kicked', 'Kicked'), ('banned', 'Banned')], default='connected', max_length=15),
        ),
    ]
