# Generated by Django 6.0 on 2025-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_room_visibility_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='called_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of called numbers [5, 13, 21]', null=True),
        ),
    ]
