# Generated by Django 6.0 on 2026-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gameround_called_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='settings_board_size',
            field=models.IntegerField(choices=[(5, '5x5 (25 numbers)'), (6, '6x6 (36 numbers)'), (7, '7x7 (49 numbers)'), (8, '8x8 (64 numbers)'), (9, '9x9 (81 numbers)'), (10, '10x10 (100 numbers)')], default=5, help_text='Board dimension (5-10)'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='called_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of called numbers [5, 13, 21]'),
        ),
        migrations.AlterField(
            model_name='roundplayer',
            name='board',
            field=models.JSONField(default=list, help_text='NxN grid based on room settings'),
        ),
    ]
